pull_request_rules:
  - name: automatic merge on approval and CI pass
    conditions:
      - '#approved-reviews-by>=1'
      - status-success=af-react-oidc-github.CI
      - label!=WIP
    actions:
      merge:
        method: squash
