pull_request_rules:
  - name: automatic merge on approval and CI pass
    conditions:
      - "#approved-reviews-by>=1"
      - status-success=SonarCloud Code Analysis
      - status-success=AxaGuilDEv.react-oidc
      - label!=WIP
    actions:
      merge:
        method: squash
