branches:
  only:
  - master
sudo: required
dist: trusty
language: node_js
node_js:
  - '8'
before_install:
  - 'npm install -g npm@^2'
install:
  - npm install
  - npm run bootstrap
script:
  - npm test -- --coverage
  - npm run lint
